language: python
sudo: false
python: "2.7.12"
install:
  - pip install -U setuptools
  - make deps
  - curl -LO https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
  - unzip consul_0.6.4_linux_amd64.zip
  - GOMAXPROCS=8 PATH=":$PATH" make start-consul
script: make ci-test
services:
  - mongodb
  - redis
notifications:
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
    - redis-server
